### PR TITLE
Rename compiler.h to cp_compiler.h

### PR DESCRIPTION
**Pull request by mgiaco**
Hi, 

I do always have some problems with compiler.h because sometimes some internal code here and there already uses a compiler.h from somewhere else. So for better explicitness we should rename compiler.h to cp_compiler.h I think.

Also I have added some compiler external definition. It is not always possible to choose one exact compiler definition especially if someone uses some custom os or so. So It would be great if you can add this.

Fix some spelling, fix inline with CPP_INLINE 

Pleas ignore the Busy Buffer stuff I will remove that in the future.

cheers
mathias

### CODE REVIEW

**Comment by microcontrol22** [comment]
The file compiler.h has been renamed to mc_compiler.h (this makes it independent from the CANpie project, so we break a naming rule here). The inline syntax inside cp_fifo.c has also been changed. Haven't changed the spelling (British English). Is it more common to use American English? Then we should change it in the hole project.

**Comment by mgiaco** [comment]
Okay but in cp_arch.h the include "compiler.h" should also be renamed to "mc_compiler.h".  I am wondering why this worked for you.

**Comment by microcontrol22** [comment]
Well, it does not work: it simply was not tested because the source directory "canpie" is deprecated and not actively maintained. Going to fix it.

**Comment by mgiaco** [comment]
Okay. many thanks

**Comment by mgiaco** [comment]
Any news here? By the way it was not only a British/American English fix there are also some typing errors inside. Or what do you mean by paramter? 

Iam wondering why you name the file mc_compiler? and not cp_compiler. Because the project name is canpie and every file starts with cp_.. so why the change in the name?

**Pull request closed without merging**
